version: 2.1

orbs:
  python: circleci/python@1.4.0
  codecov: codecov/codecov@3.3.0
  
workflows:
  buildtest:
    jobs:
      - test37
      - test38
      - test39
      - upload-codecov

commands:
  test:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install pytest
          command: |
            python --version
            pip install --upgrade pip
            pip install pytest
            pip install coverage
            pip install pytest-cov
      - run:
          name: Run tests
          command: pytest

jobs:
  upload-codecov:
    steps:
      - checkout
      - codecov/upload
  test37:
    docker:
      - image: cimg/python:3.7
    steps:
      - test

  test38:
    docker:
      - image: cimg/python:3.8
    steps:
      - test

  test39:
    docker:
      - image: cimg/python:3.9
    steps:
      - test
